<?php declare(strict_types=1);

use Folk\Sdk\Grpc\Codegen\DescriptorProvider;
use Folk\Sdk\Grpc\Codegen\ProtoGen;
use PHPUnit\Framework\TestCase;

/**
 * The generation facade: from an encoded FileDescriptorSet (the `complex.pb`
 * fixture) it writes DTOs/enums/interface to a target directory. The in-process
 * vs subprocess descriptor fetch is exercised elsewhere; here we drive the
 * write path deterministically via {@see ProtoGen::fromFds()}.
 */
final class ProtoGenTest extends TestCase
{
    private string $outDir;

    protected function setUp(): void
    {
        $this->outDir = sys_get_temp_dir() . '/folk-protogen-' . getmypid() . '-' . uniqid();
    }

    protected function tearDown(): void
    {
        if (is_dir($this->outDir)) {
            foreach (glob($this->outDir . '/*') ?: [] as $file) {
                @unlink($file);
            }
            @rmdir($this->outDir);
        }
    }

    public function testFromFdsWritesGeneratedFiles(): void
    {
        $fds = file_get_contents(__DIR__ . '/../fixtures/complex.pb');
        $this->assertNotFalse($fds);

        $written = ProtoGen::fromFds($fds, $this->outDir, 'App\\Grpc\\Generated');

        $names = array_map('basename', $written);
        $this->assertContains('Everything.php', $names);
        $this->assertContains('Inner.php', $names);
        $this->assertContains('Color.php', $names);
        $this->assertContains('ComplexServiceInterface.php', $names);

        $everything = file_get_contents($this->outDir . '/Everything.php');
        $this->assertIsString($everything);
        $this->assertStringContainsString('namespace App\\Grpc\\Generated;', $everything);
        $this->assertStringContainsString('public const FOLK_FIELDS', $everything);
        $this->assertStringContainsString('@generated by Folk', $everything);
    }

    public function testPackageLayoutWritesNestedFiles(): void
    {
        // Phase 90: a `{package}` namespace nests output into package sub-dirs and
        // the writer creates them.
        $fds = file_get_contents(__DIR__ . '/../fixtures/complex.pb');
        $this->assertNotFalse($fds);

        $written = ProtoGen::fromFds($fds, $this->outDir, 'App\\Test\\Gen\\{package}');

        $expected = $this->outDir . '/Folk/Test/Complex/Everything.php';
        $this->assertContains($expected, $written, 'nested by package folk.test.complex');
        $src = file_get_contents($expected);
        $this->assertIsString($src);
        $this->assertStringContainsString('namespace App\\Test\\Gen\\Folk\\Test\\Complex;', $src);
    }

    public function testClientNameExpandsInOutputDir(): void
    {
        // Phase 90: `{client_name}` in the out dir mirrors the namespace default
        // `.../Client/{client_name}`.
        $fds = file_get_contents(__DIR__ . '/../fixtures/complex.pb');
        $this->assertNotFalse($fds);

        $written = ProtoGen::fromFds(
            $fds,
            $this->outDir . '/Client/{client_name}',
            'App\\Gen\\Client\\{client_name}\\{package}',
            \Folk\Sdk\Grpc\Codegen\ProtoGenerator::ROLE_CLIENT,
            'catalog',
        );

        $stub = $this->outDir . '/Client/catalog/Folk/Test/Complex/ComplexServiceClient.php';
        $this->assertContains($stub, $written, 'client_name expanded in dir; package nested');
        $src = file_get_contents($stub);
        $this->assertIsString($src);
        $this->assertStringContainsString('namespace App\\Gen\\Client\\catalog\\Folk\\Test\\Complex;', $src);
    }

    public function testFromFdsCreatesNestedOutputDir(): void
    {
        $fds = file_get_contents(__DIR__ . '/../fixtures/hello.pb');
        $this->assertNotFalse($fds);

        $nested = $this->outDir . '/a/b/c';
        $written = ProtoGen::fromFds($fds, $nested, 'X\\Y');
        $this->assertNotEmpty($written);
        $this->assertDirectoryExists($nested);

        // best-effort cleanup of the deeper tree
        foreach ($written as $f) {
            @unlink($f);
        }
        @rmdir($nested);
        @rmdir($this->outDir . '/a/b');
        @rmdir($this->outDir . '/a');
    }

    public function testHasInProcessReflectsExtension(): void
    {
        $this->assertSame(function_exists('folk_grpc_descriptors'), DescriptorProvider::hasInProcess());
    }

    public function testFetchEmptyProtoListThrows(): void
    {
        $this->expectException(\RuntimeException::class);
        (new DescriptorProvider())->fetch([]);
    }
}
