<?php declare(strict_types=1);

use Folk\Sdk\Grpc\Codegen\FdsParser;
use Folk\Sdk\Grpc\Codegen\ProtoGenerator;
use Folk\Sdk\Grpc\Hydrator;
use PHPUnit\Framework\TestCase;

/**
 * End-to-end codegen: parse the `complex.pb` FileDescriptorSet fixture (built by
 * the Rust plugin from complex.proto), generate DTOs/enums/interface, load them,
 * and round-trip a wire message through the {@see Hydrator}. This is the PHP
 * counterpart to the Rust transcoding round-trip tests — together they cover the
 * full proto↔native path without protoc.
 */
final class ProtoGeneratorTest extends TestCase
{
    private const NS = 'Folk\\Sdk\\Tests\\Generated';

    /** @var array<string, string> generated relative path → source */
    private static array $generated = [];

    public static function setUpBeforeClass(): void
    {
        $fds = file_get_contents(__DIR__ . '/../fixtures/complex.pb');
        self::assertNotFalse($fds, 'complex.pb fixture present');

        $files = FdsParser::parse($fds);
        self::$generated = (new ProtoGenerator($files, self::NS))->generate();

        // Load the generated classes once (fixed namespace → no redeclare).
        $dir = sys_get_temp_dir() . '/folk-gen-' . getmypid();
        if (!is_dir($dir)) {
            mkdir($dir, 0o777, true);
        }
        foreach (self::$generated as $name => $source) {
            $path = $dir . '/' . $name;
            file_put_contents($path, $source);
            require_once $path;
        }
    }

    public function testEmitsExpectedFiles(): void
    {
        $this->assertArrayHasKey('Everything.php', self::$generated);
        $this->assertArrayHasKey('Inner.php', self::$generated);
        $this->assertArrayHasKey('Color.php', self::$generated);
        $this->assertArrayHasKey('ComplexServiceInterface.php', self::$generated);
    }

    public function testGeneratedFilesCarryHeader(): void
    {
        foreach (self::$generated as $source) {
            $this->assertStringContainsString('@generated by Folk', $source);
            $this->assertStringStartsWith("<?php", $source);
        }
    }

    public function testFolkFieldsSpecs(): void
    {
        /** @var array<string, list<mixed>> $fields */
        $fields = constant(self::NS . '\\Everything::FOLK_FIELDS');

        $this->assertSame(['s'], $fields['name']);
        $this->assertSame(['b'], $fields['blob'], 'bytes → base64 spec');
        $this->assertSame(['e', self::NS . '\\Color'], $fields['color'], 'enum spec carries the class');
        $this->assertSame(['m', self::NS . '\\Inner'], $fields['inner'], 'nested message spec');
        $this->assertSame(['r', ['s']], $fields['tags'], 'repeated scalar');
        $this->assertSame(['map', ['s']], $fields['counts'], 'map<string,int32>');
        $this->assertSame(['s'], $fields['created_at'], 'Timestamp → scalar string');
        $this->assertSame(['s'], $fields['nickname'], 'StringValue wrapper → scalar');
        $this->assertSame(['d'], $fields['extra'], 'Struct → dynamic array');
    }

    public function testInterfaceHasNameConstAndSignature(): void
    {
        $src = self::$generated['ComplexServiceInterface.php'];
        $this->assertStringContainsString("const NAME = 'folk.test.complex.ComplexService'", $src);
        $this->assertStringContainsString('public function Echo(Everything $request, Context $context): ?Everything;', $src);
    }

    public function testGeneratedEnumIsIntBacked(): void
    {
        $enum = self::NS . '\\Color';
        $this->assertTrue(enum_exists($enum));
        $this->assertSame(3, constant($enum . '::BLUE')->value);
    }

    public function testRoundTripThroughGeneratedDto(): void
    {
        $class = self::NS . '\\Everything';
        $hydrator = new Hydrator();

        $wire = [
            'name' => 'hi',
            'big' => 42,
            'ubig' => 123,
            'flag' => true,
            'blob' => base64_encode('raw'),
            'color' => 2,
            'tags' => ['x', 'y'],
            'counts' => ['a' => 1],
            'inner' => ['label' => 'L'],
            'maybe' => 'm',
            'created_at' => '2021-01-01T00:00:00Z',
            'nickname' => 'nick',
            'extra' => ['k' => 'v'],
        ];

        $dto = $hydrator->hydrate($class, $wire);
        $this->assertInstanceOf($class, $dto);
        $this->assertSame('raw', $dto->blob, 'bytes decoded in the generated DTO');
        $this->assertSame(2, $dto->color->value, 'enum hydrated to a case');

        $this->assertEquals($wire, $hydrator->dehydrate($dto), 'generated DTO round-trips the wire');
    }
}
