<?php

declare(strict_types=1);

namespace Folk\Sdk\Grpc\Codegen;

use Folk\Sdk\Grpc\Codegen\Descriptor\EnumDescriptor;
use Folk\Sdk\Grpc\Codegen\Descriptor\FieldDescriptor;
use Folk\Sdk\Grpc\Codegen\Descriptor\FileDescriptor;
use Folk\Sdk\Grpc\Codegen\Descriptor\MessageDescriptor;
use Folk\Sdk\Grpc\Codegen\Descriptor\ServiceDescriptor;

/**
 * Generates plain, readonly PHP DTOs, int-backed enums, and `*Interface`
 * service contracts from a `FileDescriptorSet` — no protoc, no protobuf runtime.
 *
 * DTO property names mirror the proto field names (snake_case), so they map 1:1
 * to the transcoded JSON the Rust plugin sends (`use_proto_field_name`). Every
 * file carries a `@generated` header; generation overwrites its target directory
 * (idempotent — decision 7).
 */
final class ProtoGenerator
{
    private const HEADER = '// @generated by Folk — do not edit';

    /** Well-known messages that transcode to a plain scalar/string (spec `['s']`). */
    private const SCALAR_WELL_KNOWN = [
        '.google.protobuf.Timestamp', '.google.protobuf.Duration', '.google.protobuf.FieldMask',
        '.google.protobuf.DoubleValue', '.google.protobuf.FloatValue',
        '.google.protobuf.Int64Value', '.google.protobuf.UInt64Value',
        '.google.protobuf.Int32Value', '.google.protobuf.UInt32Value',
        '.google.protobuf.BoolValue', '.google.protobuf.StringValue', '.google.protobuf.BytesValue',
    ];

    /** Well-known messages that stay dynamic array/mixed (spec `['d']`). */
    private const DYNAMIC_WELL_KNOWN = [
        '.google.protobuf.Struct', '.google.protobuf.Value', '.google.protobuf.ListValue',
        '.google.protobuf.Any', '.google.protobuf.Empty',
    ];

    private readonly Symbols $symbols;
    private readonly TypeMapper $types;

    /**
     * @param list<FileDescriptor> $files
     */
    public function __construct(
        private readonly array $files,
        private readonly string $namespace,
    ) {
        $this->symbols = new Symbols($files);
        $this->types = new TypeMapper($this->symbols);
    }

    /**
     * Generate all files. Returns `relativePath => phpSource` (paths are flat,
     * one class per file, named after the PHP class).
     *
     * @return array<string, string>
     */
    public function generate(): array
    {
        $out = [];

        foreach ($this->symbols->generatableEnums() as $fqn => $enum) {
            $class = $this->symbols->className($fqn) ?? $enum->name;
            $out["{$class}.php"] = $this->renderEnum($class, $enum);
        }

        foreach ($this->symbols->generatableMessages() as $fqn => $message) {
            $class = $this->symbols->className($fqn) ?? $message->name;
            $out["{$class}.php"] = $this->renderMessage($class, $message);
        }

        foreach ($this->files as $file) {
            foreach ($file->services as $service) {
                $name = "{$service->name}Interface";
                $out["{$name}.php"] = $this->renderInterface($file, $service);
            }
        }

        return $out;
    }

    private function renderEnum(string $class, EnumDescriptor $enum): string
    {
        $cases = '';
        foreach ($enum->values as $value) {
            $cases .= "    case {$value->name} = {$value->number};\n";
        }

        return $this->file(<<<PHP
            enum {$class}: int
            {
            {$cases}}
            PHP);
    }

    private function renderMessage(string $class, MessageDescriptor $message): string
    {
        $params = [];
        $docLines = [];
        $specs = [];
        foreach ($message->fields as $field) {
            $type = $this->types->forField($field);
            if ($type->doc !== null) {
                $docLines[] = "     * @param {$type->doc} \${$field->name}";
            }
            $params[] = "        public {$type->declared} \${$field->name} = {$type->default},";
            $specs[] = "        '{$field->name}' => {$this->fieldSpec($field)},";
        }

        // FOLK_FIELDS drives the runtime Hydrator (array↔DTO); see
        // {@see \Folk\Sdk\Grpc\Hydrator}. Emitted for every message so the
        // hydrator can round-trip without protoc or reflection guesswork.
        $fieldsConst = "    /** @var array<string, list<mixed>> */\n    public const FOLK_FIELDS = [";
        $fieldsConst .= $specs === [] ? '];' : "\n" . implode("\n", $specs) . "\n    ];";

        $body = $fieldsConst . "\n\n";
        if ($docLines !== []) {
            $body .= "    /**\n" . implode("\n", $docLines) . "\n     */\n";
        }
        $body .= "    public function __construct(";
        if ($params !== []) {
            $body .= "\n" . implode("\n", $params) . "\n    ";
        }
        $body .= ") {}";

        return $this->file(<<<PHP
            final readonly class {$class}
            {
            {$body}
            }
            PHP);
    }

    private function renderInterface(FileDescriptor $file, ServiceDescriptor $service): string
    {
        $fqName = $file->package === '' ? $service->name : "{$file->package}.{$service->name}";
        $methods = '';
        foreach ($service->methods as $method) {
            if ($method->clientStreaming || $method->serverStreaming) {
                $methods .= "    // {$method->name}: streaming RPC — not supported by transcoding (phase 87)\n";
                continue;
            }
            $in = $this->symbols->className($method->inputType) ?? 'array';
            $out = $this->symbols->className($method->outputType) ?? 'array';
            // Nullable return: a handler reports a business outcome via
            // $context->setStatus() and returns null (standard gRPC idiom).
            $methods .= "    public function {$method->name}({$in} \$request, Context \$context): ?{$out};\n";
        }

        $body = "    public const NAME = '{$fqName}';\n\n{$methods}";

        return $this->file(
            <<<PHP
            interface {$service->name}Interface extends ServiceInterface
            {
            {$body}}
            PHP,
            ["use Folk\\Sdk\\Grpc\\Context;", "use Folk\\Sdk\\Grpc\\ServiceInterface;"],
        );
    }

    /**
     * The `FOLK_FIELDS` spec literal for one field — a PHP array literal the
     * {@see \Folk\Sdk\Grpc\Hydrator} interprets. Repeated wraps `['r', <elem>]`,
     * map wraps `['map', <value>]` (proto map keys are always scalar).
     */
    private function fieldSpec(FieldDescriptor $field): string
    {
        if ($field->isRepeated()) {
            if ($field->type === ProtoType::TYPE_MESSAGE && $this->symbols->isMapEntry($field->typeName)) {
                $entry = $this->symbols->message($field->typeName);
                $valueSpec = "['d']";
                if ($entry !== null) {
                    foreach ($entry->fields as $entryField) {
                        if ($entryField->number === 2) {
                            $valueSpec = $this->singularSpec($entryField);
                        }
                    }
                }
                return "['map', {$valueSpec}]";
            }
            return "['r', {$this->singularSpec($field)}]";
        }
        return $this->singularSpec($field);
    }

    /** The singular (label-stripped) spec literal for a field. */
    private function singularSpec(FieldDescriptor $field): string
    {
        return match ($field->type) {
            ProtoType::TYPE_MESSAGE => $this->messageSpec($field->typeName),
            ProtoType::TYPE_ENUM => ($class = $this->symbols->className($field->typeName)) !== null
                ? "['e', {$class}::class]"
                : "['s']",
            ProtoType::TYPE_BYTES => "['b']",
            default => "['s']",
        };
    }

    /** Spec literal for a message-typed field (well-known aware). */
    private function messageSpec(string $typeName): string
    {
        if (in_array($typeName, self::DYNAMIC_WELL_KNOWN, true)) {
            return "['d']";
        }
        if (in_array($typeName, self::SCALAR_WELL_KNOWN, true)) {
            return "['s']";
        }
        $class = $this->symbols->className($typeName);
        return $class !== null ? "['m', {$class}::class]" : "['d']";
    }

    /**
     * Wrap a class/enum/interface body in the file preamble (strict types,
     * `@generated`, namespace, optional imports).
     *
     * @param list<string> $uses
     */
    private function file(string $body, array $uses = []): string
    {
        $useBlock = $uses === [] ? '' : implode("\n", $uses) . "\n\n";
        return "<?php\n\n"
            . "declare(strict_types=1);\n\n"
            . self::HEADER . "\n\n"
            . "namespace {$this->namespace};\n\n"
            . $useBlock
            . $body . "\n";
    }
}
