<?php

declare(strict_types=1);

namespace Folk\Sdk\Grpc\Codegen;

use Folk\Sdk\Grpc\Codegen\Descriptor\EnumDescriptor;
use Folk\Sdk\Grpc\Codegen\Descriptor\FieldDescriptor;
use Folk\Sdk\Grpc\Codegen\Descriptor\FileDescriptor;
use Folk\Sdk\Grpc\Codegen\Descriptor\MessageDescriptor;
use Folk\Sdk\Grpc\Codegen\Descriptor\MethodDescriptor;
use Folk\Sdk\Grpc\Codegen\Descriptor\ServiceDescriptor;

/**
 * Generates plain, readonly PHP DTOs, int-backed enums, and — depending on the
 * role — either server `*Interface` contracts or client `*Client` stubs from a
 * `FileDescriptorSet`. No protoc, no protobuf runtime.
 *
 * DTO property names mirror the proto field names (snake_case), so they map 1:1
 * to the transcoded JSON the Rust plugin sends (`use_proto_field_name`). Every
 * file carries a `@generated` header; generation overwrites its target directory
 * (idempotent — decision 7).
 *
 * Role (phase 88):
 *  - `server` (default) — emit `{Service}Interface` you implement.
 *  - `client` — emit `{Service}Client extends GrpcClient` you call; the stub bakes
 *    the `[grpc.clients.<name>]` client name so it resolves the right upstream.
 * DTOs/enums are emitted the same way for both roles.
 */
final class ProtoGenerator
{
    public const ROLE_SERVER = 'server';
    public const ROLE_CLIENT = 'client';

    private const HEADER = '// @generated by Folk — do not edit';

    /** Well-known messages that transcode to a plain scalar/string (spec `['s']`). */
    private const SCALAR_WELL_KNOWN = [
        '.google.protobuf.Timestamp', '.google.protobuf.Duration', '.google.protobuf.FieldMask',
        '.google.protobuf.DoubleValue', '.google.protobuf.FloatValue',
        '.google.protobuf.Int64Value', '.google.protobuf.UInt64Value',
        '.google.protobuf.Int32Value', '.google.protobuf.UInt32Value',
        '.google.protobuf.BoolValue', '.google.protobuf.StringValue', '.google.protobuf.BytesValue',
    ];

    /** Well-known messages that stay dynamic array/mixed (spec `['d']`). */
    private const DYNAMIC_WELL_KNOWN = [
        '.google.protobuf.Struct', '.google.protobuf.Value', '.google.protobuf.ListValue',
        '.google.protobuf.Any', '.google.protobuf.Empty',
    ];

    private readonly Symbols $symbols;
    private readonly TypeMapper $types;

    /**
     * @param list<FileDescriptor> $files
     * @param self::ROLE_* $role       server (`*Interface`) or client (`*Client`)
     * @param string       $clientName the `[grpc.clients.<name>]` name baked into
     *                                  generated client stubs (client role only)
     */
    public function __construct(
        private readonly array $files,
        private readonly string $namespace,
        private readonly string $role = self::ROLE_SERVER,
        private readonly string $clientName = '',
    ) {
        $this->symbols = new Symbols($files);
        $this->types = new TypeMapper($this->symbols);
    }

    /**
     * Generate all files. Returns `relativePath => phpSource`. When the target
     * namespace contains `{package}` (phase 90), each class is placed in a
     * package-derived sub-namespace and the path mirrors it (e.g.
     * `Io/Altessa/Serviceinfo/V1/ServiceInfo.php`); otherwise the flat layout is
     * preserved (`ServiceInfo.php`).
     *
     * @return array<string, string>
     */
    public function generate(): array
    {
        $out = [];

        foreach ($this->symbols->generatableEnums() as $fqn => $enum) {
            $class = $this->symbols->className($fqn) ?? $enum->name;
            $pkg = $this->symbols->package($fqn);
            $out[$this->path($pkg, $class)] = $this->renderEnum($class, $enum, $this->namespaceFor($pkg));
        }

        foreach ($this->symbols->generatableMessages() as $fqn => $message) {
            $class = $this->symbols->className($fqn) ?? $message->name;
            $pkg = $this->symbols->package($fqn);
            $out[$this->path($pkg, $class)] = $this->renderMessage($class, $message, $this->namespaceFor($pkg));
        }

        foreach ($this->files as $file) {
            $ns = $this->namespaceFor($file->package);
            foreach ($file->services as $service) {
                if ($this->role === self::ROLE_CLIENT) {
                    $out[$this->path($file->package, "{$service->name}Client")]
                        = $this->renderClient($file, $service, $ns);
                } else {
                    $out[$this->path($file->package, "{$service->name}Interface")]
                        = $this->renderInterface($file, $service, $ns);
                }
            }
        }

        return $out;
    }

    /**
     * The PHP namespace for a symbol of proto `$package`: the target template with
     * `{client_name}` and `{package}` expanded (phase 90). No `{package}` → flat
     * template (BC). `{package}` with the unnamed package collapses the segment.
     */
    private function namespaceFor(string $package): string
    {
        $ns = str_replace('{client_name}', $this->clientName, $this->namespace);
        $pkgNs = Symbols::packageToNs($package);
        if (str_contains($ns, '{package}')) {
            $ns = $pkgNs === ''
                ? str_replace(['\\{package}', '{package}'], '', $ns)
                : str_replace('{package}', $pkgNs, $ns);
        }

        return trim($ns, '\\');
    }

    /** Output path (relative to the generated dir) for a class of `$package`. */
    private function path(string $package, string $class): string
    {
        $sub = str_contains($this->namespace, '{package}')
            ? str_replace('\\', '/', Symbols::packageToNs($package))
            : '';

        return ($sub === '' ? '' : "{$sub}/") . "{$class}.php";
    }

    /**
     * The PHP reference to a message/enum from within `$currentNs` (phase 90):
     * short name when the type shares the namespace, otherwise a leading-`\` FQN.
     * Null when the type is not a generatable symbol (caller falls back to array).
     */
    private function typeRef(string $fqn, string $currentNs): ?string
    {
        $short = $this->symbols->className($fqn);
        if ($short === null) {
            return null;
        }
        $ns = $this->namespaceFor($this->symbols->package($fqn));
        if ($ns === $currentNs) {
            return $short;
        }
        return '\\' . ($ns === '' ? $short : "{$ns}\\{$short}");
    }

    private function renderEnum(string $class, EnumDescriptor $enum, string $ns): string
    {
        $cases = '';
        foreach ($enum->values as $value) {
            $cases .= "    case {$value->name} = {$value->number};\n";
        }

        return $this->file($ns, <<<PHP
            enum {$class}: int
            {
            {$cases}}
            PHP);
    }

    private function renderMessage(string $class, MessageDescriptor $message, string $ns): string
    {
        // Cross-package field types resolve to a leading-`\` FQN, same-package to a
        // short name (phase 90).
        $refFor = fn (string $fqn): string => $this->typeRef($fqn, $ns) ?? '';

        $params = [];
        $docLines = [];
        $specs = [];
        foreach ($message->fields as $field) {
            $type = $this->types->forField($field, $refFor);
            if ($type->doc !== null) {
                $docLines[] = "     * @param {$type->doc} \${$field->name}";
            }
            $params[] = "        public {$type->declared} \${$field->name} = {$type->default},";
            $specs[] = "        '{$field->name}' => {$this->fieldSpec($field, $ns)},";
        }

        // FOLK_FIELDS drives the runtime Hydrator (array↔DTO); see
        // {@see \Folk\Sdk\Grpc\Hydrator}. Emitted for every message so the
        // hydrator can round-trip without protoc or reflection guesswork.
        $fieldsConst = "    /** @var array<string, list<mixed>> */\n    public const FOLK_FIELDS = [";
        $fieldsConst .= $specs === [] ? '];' : "\n" . implode("\n", $specs) . "\n    ];";

        $body = $fieldsConst . "\n\n";
        if ($docLines !== []) {
            $body .= "    /**\n" . implode("\n", $docLines) . "\n     */\n";
        }
        $body .= "    public function __construct(";
        if ($params !== []) {
            $body .= "\n" . implode("\n", $params) . "\n    ";
        }
        $body .= ") {}";

        return $this->file($ns, <<<PHP
            final readonly class {$class}
            {
            {$body}
            }
            PHP);
    }

    private function renderInterface(FileDescriptor $file, ServiceDescriptor $service, string $ns): string
    {
        $fqName = $file->package === '' ? $service->name : "{$file->package}.{$service->name}";
        $methods = '';
        foreach ($service->methods as $method) {
            $in = $this->typeRef($method->inputType, $ns) ?? 'array';
            $out = $this->typeRef($method->outputType, $ns) ?? 'array';

            // Server-streaming (phase 88b, #32): the handler yields response DTOs;
            // the WorkerLoop frames each. One request in, a stream of `$out` out.
            if ($method->serverStreaming && !$method->clientStreaming) {
                $methods .= "    /** @return iterable<{$out}> */\n";
                $methods .= "    public function {$method->name}({$in} \$request, Context \$context): iterable;\n";
                continue;
            }

            // Client-streaming / bidi on the SERVER are not supported in v1 (the
            // server does not yet feed an inbound request stream to PHP). The
            // client stub handles all three kinds; only the server half is limited.
            // (Reaching here, server-streaming-only was already handled above, so a
            // remaining streaming method is necessarily client-streaming or bidi.)
            if ($method->clientStreaming) {
                $methods .= "    // {$method->name}: client-streaming/bidi server handler — not supported (v1; server → later)\n";
                continue;
            }

            // Unary. Nullable return: a handler reports a business outcome via
            // $context->setStatus() and returns null (standard gRPC idiom).
            $methods .= "    public function {$method->name}({$in} \$request, Context \$context): ?{$out};\n";
        }

        $body = "    public const NAME = '{$fqName}';\n\n{$methods}";

        return $this->file(
            $ns,
            <<<PHP
            interface {$service->name}Interface extends ServiceInterface
            {
            {$body}}
            PHP,
            ["use Folk\\Sdk\\Grpc\\Context;", "use Folk\\Sdk\\Grpc\\ServiceInterface;"],
        );
    }

    /**
     * Render a client stub `{Service}Client extends GrpcClient` (phase 88): one
     * typed method per unary RPC that dehydrates the request, calls
     * `grpc.client.call`, and hydrates the response. The `CLIENT` constant binds
     * the stub to a `[grpc.clients.<name>]` entry; `SERVICE` is the proto service
     * FQN. Streaming methods are skipped (unary only in phase 88; streaming → #32).
     */
    private function renderClient(FileDescriptor $file, ServiceDescriptor $service, string $ns): string
    {
        $fqName = $file->package === '' ? $service->name : "{$file->package}.{$service->name}";

        // A service that mixes unary and streaming RPCs extends the streaming base
        // (which IS-A GrpcClient), so both kinds live on one stub. Unary-only
        // services keep the leaner GrpcClient base (phase-88 output unchanged).
        $hasStreaming = false;
        foreach ($service->methods as $method) {
            if ($method->clientStreaming || $method->serverStreaming) {
                $hasStreaming = true;
                break;
            }
        }
        $base = $hasStreaming ? 'GrpcStreamClient' : 'GrpcClient';

        $methods = '';
        foreach ($service->methods as $method) {
            if ($method->clientStreaming || $method->serverStreaming) {
                $methods .= $this->renderClientStreamMethod($method, $ns);
                continue;
            }
            $in = $this->typeRef($method->inputType, $ns);
            $out = $this->typeRef($method->outputType, $ns);

            if ($in !== null && $out !== null) {
                // The common, fully-typed path: DTO in → DTO out.
                $methods .= <<<PHP
                        public function {$method->name}({$in} \$request): {$out}
                        {
                            return \$this->call('{$method->name}', \$request, {$out}::class);
                        }


                    PHP;
            } else {
                // Fallback for non-generatable message types: exchange raw arrays.
                $methods .= <<<PHP
                        /**
                         * @param array<string, mixed> \$request
                         * @return array<string, mixed>
                         */
                        public function {$method->name}(array \$request): array
                        {
                            return \$this->callArray('{$method->name}', \$request);
                        }


                    PHP;
            }
        }

        $body = "    public const CLIENT = '{$this->clientName}';\n"
            . "    public const SERVICE = '{$fqName}';\n\n"
            . rtrim($methods, "\n") . "\n";

        return $this->file(
            $ns,
            <<<PHP
            final class {$service->name}Client extends {$base}
            {
            {$body}}
            PHP,
            ["use Folk\\Sdk\\Grpc\\Client\\{$base};"],
        );
    }

    /**
     * Render one client-stub method for a streaming RPC (phase 88b, #32):
     * server-streaming (`In` → `iterable<Out>`), client-streaming
     * (`iterable<In>` → `Out`), or bidi (`iterable<In>` → `iterable<Out>`). Falls
     * back to raw-array exchange when a message type is not a generatable DTO.
     */
    private function renderClientStreamMethod(MethodDescriptor $method, string $ns): string
    {
        $in = $this->typeRef($method->inputType, $ns);
        $out = $this->typeRef($method->outputType, $ns);
        $name = $method->name;
        $typed = $in !== null && $out !== null;

        // Server-streaming: one request → a lazy stream of responses.
        if ($method->serverStreaming && !$method->clientStreaming) {
            if ($typed) {
                return <<<PHP
                        /** @return \Generator<int, {$out}> */
                        public function {$name}({$in} \$request): \Generator
                        {
                            return \$this->serverStream('{$name}', \$request, {$out}::class);
                        }


                    PHP;
            }
            return <<<PHP
                    /**
                     * @param array<string, mixed> \$request
                     * @return \Generator<int, array<string, mixed>>
                     */
                    public function {$name}(array \$request): \Generator
                    {
                        return \$this->serverStreamArray('{$name}', \$request);
                    }


                PHP;
        }

        // Client-streaming: a stream of requests → one response.
        if ($method->clientStreaming && !$method->serverStreaming) {
            if ($typed) {
                return <<<PHP
                        /** @param iterable<{$in}> \$requests */
                        public function {$name}(iterable \$requests): {$out}
                        {
                            return \$this->clientStream('{$name}', \$requests, {$out}::class);
                        }


                    PHP;
            }
            return <<<PHP
                    /**
                     * @param iterable<array<string, mixed>> \$requests
                     * @return array<string, mixed>
                     */
                    public function {$name}(iterable \$requests): array
                    {
                        return \$this->clientStreamArray('{$name}', \$requests);
                    }


                PHP;
        }

        // Bidirectional streaming (v1 serialized — see GrpcStreamClient).
        if ($typed) {
            return <<<PHP
                    /**
                     * @param iterable<{$in}> \$requests
                     * @return \Generator<int, {$out}>
                     */
                    public function {$name}(iterable \$requests): \Generator
                    {
                        return \$this->bidiStream('{$name}', \$requests, {$out}::class);
                    }


                PHP;
        }
        return <<<PHP
                /**
                 * @param iterable<array<string, mixed>> \$requests
                 * @return \Generator<int, array<string, mixed>>
                 */
                public function {$name}(iterable \$requests): \Generator
                {
                    return \$this->bidiStreamArray('{$name}', \$requests);
                }


            PHP;
    }

    /**
     * The `FOLK_FIELDS` spec literal for one field — a PHP array literal the
     * {@see \Folk\Sdk\Grpc\Hydrator} interprets. Repeated wraps `['r', <elem>]`,
     * map wraps `['map', <value>]` (proto map keys are always scalar).
     */
    private function fieldSpec(FieldDescriptor $field, string $ns): string
    {
        if ($field->isRepeated()) {
            if ($field->type === ProtoType::TYPE_MESSAGE && $this->symbols->isMapEntry($field->typeName)) {
                $entry = $this->symbols->message($field->typeName);
                $valueSpec = "['d']";
                if ($entry !== null) {
                    foreach ($entry->fields as $entryField) {
                        if ($entryField->number === 2) {
                            $valueSpec = $this->singularSpec($entryField, $ns);
                        }
                    }
                }
                return "['map', {$valueSpec}]";
            }
            return "['r', {$this->singularSpec($field, $ns)}]";
        }
        return $this->singularSpec($field, $ns);
    }

    /** The singular (label-stripped) spec literal for a field. */
    private function singularSpec(FieldDescriptor $field, string $ns): string
    {
        return match ($field->type) {
            ProtoType::TYPE_MESSAGE => $this->messageSpec($field->typeName, $ns),
            // `::class` must be a leading-`\` FQN for a cross-package enum, else the
            // Hydrator would resolve it against the current namespace (phase 90).
            ProtoType::TYPE_ENUM => ($ref = $this->typeRef($field->typeName, $ns)) !== null
                ? "['e', {$ref}::class]"
                : "['s']",
            ProtoType::TYPE_BYTES => "['b']",
            default => "['s']",
        };
    }

    /** Spec literal for a message-typed field (well-known aware). */
    private function messageSpec(string $typeName, string $ns): string
    {
        if (in_array($typeName, self::DYNAMIC_WELL_KNOWN, true)) {
            return "['d']";
        }
        if (in_array($typeName, self::SCALAR_WELL_KNOWN, true)) {
            return "['s']";
        }
        $ref = $this->typeRef($typeName, $ns);
        return $ref !== null ? "['m', {$ref}::class]" : "['d']";
    }

    /**
     * Wrap a class/enum/interface body in the file preamble (strict types,
     * `@generated`, namespace, optional imports).
     *
     * @param list<string> $uses
     */
    private function file(string $namespace, string $body, array $uses = []): string
    {
        $useBlock = $uses === [] ? '' : implode("\n", $uses) . "\n\n";
        return "<?php\n\n"
            . "declare(strict_types=1);\n\n"
            . self::HEADER . "\n\n"
            . "namespace {$namespace};\n\n"
            . $useBlock
            . $body . "\n";
    }
}
